version: '3'
services:
  emqx-enterprise:
    image: emqx/emqx-enterprise:5.0.3
    # command: /opt/entrypoint.sh
    container_name: emqx-enterprise
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      - emqx-net
    volumes:
      - $PWD/cluster.hocon:/opt/emqx/data/configs/cluster.hocon
    depends_on:
      - kafka
    

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - emqx-net

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-vehicles:1:1"
    networks:
      - emqx-net
    depends_on:
      - zookeeper

networks:
  emqx-net:
    driver: bridge
